#!/bin/bash
#This script lets the user select videos to play in vlc

#echo "Enter the directory of the video library: "

if [ $1 = '-s' ]
then
	videodir=$2
	echo "You will need to close the VLC window to start the next video!"
	select=$( ls -h $videodir | dmenu -l 30 | xargs )
	lines=$( ls -h $videodir | wc -l)
	position=$( ls -h $videodir | grep -n $select | cut -d ":" -f 1 )
	lines_remaining=$(echo `expr $lines - $position`)
	lines_remaining=$(( $lines_remaining + 1 ))
	select=$( ls -h $videodir | tail -$lines_remaining )
	for x in $select
	do
		select="$videodir$x"
		echo $select | xargs vlc >/dev/null 2>&1
	done
else
	videodir=$1
	select=$( ls -h $videodir | dmenu -l 30 | xargs)
	select="$videodir$select"
	echo $select | xargs vlc >/dev/null 2>&1
fi
